### ISSUE TITLE
Page redirect bug

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#136] opened 2023-07-16 18:54 UTC
### Resource

WemX Pro

### Describe the issue

When creating a custom page in admin area there is an option to redirect to a URL, but this unfortunately does not work. When clicking save the url imputed into the field simply just disappears. 

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.2.0

### To Reproduce

1. Create page in admin area
2. Add a url to redirect and save
3. Doesnt work

**Comment by GIGABAIT93** [comment] 2023-08-06 20:39
Please check it again because I didn't see any errors while testing

**Comment by Mubeen142** [comment] 2023-09-02 17:08
Hi @Shockingg 

I was unable to reproduce this issue. Perhaps it was fixed in a previous update. Feel free to reopen the issue if you believe this is false

**Closed by Mubeen142** 2023-09-02 17:08 UTC
Labels: bug, wemx
