### ISSUE TITLE
Chat with support

### ISSUE THREAD

**Issue by IkdanYT** [VertisanPRO/pterodactyl#492] opened 2024-08-04 20:17 UTC
### Describe the solution you'd like

Convenient chat in the corner (customisable location, colours and so on) with support like on many big company websites.

**Comment by IkdanYT** [comment] 2024-08-04 20:20
> ### Describe the solution you'd like
> Convenient chat in the corner (customisable location, colours and so on) with support like on many big company websites.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

It would also be nice to add AI model integration with a custom prompt-instruction. Api key, token, or preferably the whole request at once, just with placeholders from other fields (api key, api base, instruction and so on should be customised and be placeholders for another field with sending POST request to the neural network API).

**Comment by PadowYT2** [comment] 2024-08-05 11:38
Duplicate of #450

**Closed as not planned by PadowYT2** 2024-08-05 11:38 UTC
Labels: duplicate, enhancement, wontfix
