### ISSUE TITLE
Player configuration Plan

### ISSUE THREAD

**Issue by SiFuMax09** [VertisanPRO/pterodactyl#259] opened 2023-11-05 15:09 UTC
### Product

WemX Pro

### Describe the solution you'd like

A Funktion that a player can configure a plan himself and the price will be calculated. I can set a price for 1 GB and if the user want 5 Gb ram the user get 5 GB ram.

**Comment by PadowYT2** [comment] 2023-11-05 15:11
Duplicate of #238

**Closed** 2023-11-05 15:11 UTC
Labels: duplicate, enhancement, invalid, wemx
