### ISSUE TITLE
Sliders for the Shop

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/pterodactyl#215] opened 2023-09-28 07:42 UTC
### Product

WemX Pro

### Describe the solution you'd like

Make it possible to add Sliders as a Option to select as Example the Ram or so for a Gameserver like Minecraft out of a given Range.

**Comment by VanillaChan6571** [comment] 2023-09-28 08:18
Duplicate of #200

**Closed** 2023-09-28 08:18 UTC
Labels: duplicate, enhancement, question, wemx
