### ISSUE TITLE
[Feature Request] Choosing eggs to choose from when customer purchases a server.

### ISSUE THREAD

**Issue by XceptDev** [VertisanPRO/pterodactyl#438] opened 2024-04-22 17:35 UTC
### Describe the solution you'd like

Ability to choose a few pterodactyl eggs so customer will have ability to chose for example if he wants node.js or python server. It would be just like the customer can select the node. Currently, to add a node list for product, you chave to press Control on keyboard and choose the desired nodes. Please add this option to eggs aswell. People want this feature..

**Comment by PadowYT2** [comment] 2024-04-22 17:36
Duplicate of #238

**Closed as not planned by PadowYT2** 2024-04-22 17:36 UTC
Labels: duplicate, enhancement, invalid

**Comment by XceptDev** [comment] 2024-04-27 18:10
I don't understand how a wanted by people feature is "not planned"

**Comment by PadowYT2** [comment] 2024-04-27 18:10
> I don't understand how a wanted by people feature is "not planned"

Read my message
