### ISSUE TITLE
better Discord Integration

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/pterodactyl#189] opened 2023-09-07 18:11 UTC
### Resource

WemX Pro

### Describe the solution you'd like

it would be nice, if it would be possible to let Users automatically join our Discord Server and then also give them the "buyer" Role or so and also sync Roles like Supporter, Admin and such things.
Another great feature would be a messaging Feature with Embeds in Discord besides E-Mail and also Messages like "A new Server was bought by xyz" or so

**Comment by PadowYT2** [comment] 2023-10-17 18:58
Duplicate of #121

**Closed by PadowYT2** 2023-10-17 18:58 UTC
Labels: duplicate, enhancement, invalid, wemx
