### ISSUE TITLE
Less code, more customisation

### ISSUE THREAD

**Issue by IkdanYT** [VertisanPRO/pterodactyl#494] opened 2024-08-04 20:25 UTC
### Describe the solution you'd like

I would like to see a client panel that is FULLY customisable from the admin panel. Creating gateways, modules, custom systems, tabs and so on through the admin panel with minimal coding. At least convenient constructors of extensions and GateWays.

**Comment by IkdanYT** [comment] 2024-08-04 20:26
> ### Describe the solution you'd like
> I would like to see a client panel that is FULLY customisable from the admin panel. Creating gateways, modules, custom systems, tabs and so on through the admin panel with minimal coding. At least convenient constructors of extensions and GateWays.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

Customisation of the interface as well as the portal, requiring only the installation of placeholders, with the ability to move, change and so on.

**Comment by PadowYT2** [comment] 2024-08-05 11:40
Duplicate of a lot of issues

**Closed as not planned by PadowYT2** 2024-08-05 11:40 UTC
Labels: duplicate, enhancement, invalid, wontfix
