### ISSUE TITLE
Incorrect text after an SSO login

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#422] opened 2024-04-01 18:09 UTC
### Describe the issue

If I now log in with Discord everything works fine, but it says "That I have successfully connected discord to my account" but that makes no sense because I log in with it and I am wrongly redirected to /settings
![image](https://github.com/WemXPro/tracker/assets/53320411/490156fe-b709-4956-b6e6-f6e32c1bbc57)

### Product Version

2.1.0

### Pterodactyl Panel Version (if applicable)

-

### To Reproduce

-

**Comment by VanillaChan6571** [comment] 2024-04-08 08:50
Unable to reproduce.

**Comment by GIGABAIT93** [comment] 2024-04-10 06:13
Will be fixed in the next wemx update

**Closed as completed by GIGABAIT93** 2024-04-10 06:13 UTC
Labels: bug
