### ISSUE TITLE
Trial Plans

### ISSUE THREAD

**Issue by RobertGreen-25** [VertisanPRO/pterodactyl#511] opened 2024-09-11 17:39 UTC
### Describe the solution you'd like

Allow us to create trials for like 7 days or 30 days then after the trial has finished the server will get suspended unless they request to keep the server and then pay a invoice to change it monthly payment so it will come out of trial period

**Comment by PadowYT2** [comment] 2024-09-11 20:26
Duplicate of WemXPro/tracker#490

**Closed as not planned by PadowYT2** 2024-09-11 20:26 UTC
Labels: duplicate, enhancement, invalid, service
