### ISSUE TITLE
Egg Switcher

### ISSUE THREAD

**Issue by ogsaiko** [VertisanPRO/pterodactyl#484] opened 2024-07-15 16:47 UTC
### Describe the solution you'd like

The ability to switch selected eggs in a dropdown in either the package or the checkout page

I.e. For a Minecraft package, the ability to switch from Vanilla to Paper, Spigot, or Forge, or a Terraria package that can select vanilla or tModLoader

### Describe alternatives you've considered

Creating seperate packages with labels indicating what egg they are running on, the issue with this being that if we want the choice of five different eggs, we need five different packages for each "package" leading to 5 packages becoming 25

**Comment by PadowYT2** [comment] 2024-07-15 19:33
Duplicate of WemXPro/tracker#238

**Closed as not planned by PadowYT2** 2024-07-15 19:33 UTC
Labels: duplicate, enhancement, invalid
