### ISSUE TITLE
ipqualityscore.com and detecting abusive accounts

### ISSUE THREAD

**Issue by IkdanYT** [VertisanPRO/pterodactyl#505] opened 2024-08-11 09:25 UTC
### Describe the solution you'd like

Add duplicate account detection and the ability to set them up automatically on manual verification, exactly the same thing to do with VPNs.
You can use ipqualityscore functions.
Configuration through a separate category, can be made a module.
In the settings the possibility to configure all parameters with api key.

**Comment by PadowYT2** [comment] 2024-08-13 11:46
Duplicate of #265

**Closed as not planned by PadowYT2** 2024-08-13 11:46 UTC
Labels: duplicate, enhancement
