### ISSUE TITLE
Subscriptions missing

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#173] opened 2023-08-05 10:30 UTC
### Resource

WemX Pro

### Describe the issue

since the last update there is nothing to see at /subscriptions although a user has a subscription

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0

### To Reproduce

since the last update there is nothing to see at /subscriptions although a user has a subscription

**Comment by VanillaChan6571** [comment] 2023-08-06 23:29
Not really a bug, since most of your subscriptions/packages are in the user's dashboard.

More less it should really be marked as "what is this for?"

**Comment by Partymann2000** [comment] 2023-08-06 23:52
since the last update, subs are no longer displayed for the user

**Comment by Mubeen142** [comment] 2023-09-02 19:19
Hey @Partymann2000 

I believe this bug was already fixed in a previous update. If you think that is false, please reopen the issue with exact steps to reproduce the issue

**Closed by Mubeen142** 2023-09-02 19:19 UTC
Labels: bug, wemx
