### ISSUE TITLE
Supplement for the DiscordConnect module

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#504] opened 2024-08-08 10:02 UTC
### Describe the solution you'd like

A possibility to add as an event the addition of your discord acocunt, so that when you link your dsicord d, you automatically get a nrole, and when you unlinked then the role is withdrawn again.

**Comment by RobertGreen-25** [comment] 2024-08-08 13:52
that feature has already been implanted

**Comment by RobertGreen-25** [comment] 2024-08-08 13:55
Good Idea but that could be done through packages such as when they buy a package the role will be given but if the service gets suspended / terminated you can make the event remove the role

**Comment by PadowYT2** [comment] 2024-08-09 14:37
Duplicate of #121

**Closed as not planned by PadowYT2** 2024-08-09 14:37 UTC
Labels: duplicate, enhancement, invalid
