### ISSUE TITLE
Configurable Options

### ISSUE THREAD

**Issue by expxx** [VertisanPRO/pterodactyl#213] opened 2023-09-26 20:18 UTC
### Product

WemX Pro

### Describe the solution you'd like

I'm not entirely sure how one to explain this, but a dropdown, slider, or text field, that can have a value. That value would get replaced in the product settings. For example, a configurable options for memory. A dropdown that has 1GB, 3GB, and 5GB. The customer can select which one, and that'd override product settings configured in Wemx and use the configurable option value instead.

(If you can't understand my words, here's what I'm trying to replicate https://docs.whmcs.com/Configurable_Options)

**Comment by VanillaChan6571** [comment] 2023-09-27 01:34
Duplicate of #200

**Closed** 2023-09-27 01:40 UTC
Labels: duplicate, enhancement, question, wemx
