### ISSUE TITLE
Form not working BUG

### ISSUE THREAD

**Issue by DenDanskeMine** [VertisanPRO/pterodactyl#221] opened 2023-10-01 19:05 UTC
### Product

WemX Pro

## Issue: Contact Us Form Email Submission Problem

**Problem Description:**

- Emails sent via the Contact Us form are not being received.
- Despite showing a green success alert, the emails are not actually sent.
- The alert shows up 2 places.

**Also a Suggestion:**

 **Implement Email Confirmation:**  Consider sending an automated acknowledgment email to users upon form submission. This email should confirm that we've received their message and will respond as soon as possible. This will provide transparency to users.
 
Maybe this is a feature, but as the form is not working for me, i have no way of knowing.

### Pterodactyl Panel Version

1.11.3

### Product Version

v1.7.0

### To Reproduce

Try sending a mail, through  the contact us form

### Expected Behaviour

Email should be send, to our inbox

### Screenshots

https://gyazo.com/d4a903e7cd18efe67ac7b036c5f88417

**Comment by PadowYT2** [comment] 2023-10-01 19:13
Duplicate of #203

**Closed by PadowYT2** 2023-10-01 19:13 UTC
Labels: bug, duplicate, question, wemx
