### ISSUE TITLE
VErification problem

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#418] opened 2024-03-24 00:31 UTC
### Describe the issue

If you register and go to back to login, it doesn't go exactly the same way where you have to enter the code you received

### Product Version

2.0.1

### Pterodactyl Panel Version (if applicable)

x

**Comment by VanillaChan6571** [comment] 2024-03-24 09:49
Duplicate of #117 and #412

**Comment by PadowYT2** [comment] 2024-03-24 10:57
Duplicate of #278

**Closed as not planned by PadowYT2** 2024-03-24 10:57 UTC
Labels: bug, duplicate, invalid
